### ISSUE TITLE
error message with Rundeck authenticating to Windows with pywinrm Credssp

### ISSUE THREAD

**Issue by cwaltherf** [jborean93/requests-credssp#11]
While running a job with pywinrm plugin in Rundeck to a Windows 2012 R2 server host with Credssp authentication, we are receiving this error message only on a particular environment.

"authenticationexception server did not response with a credssp token after step 1 tls handshake actual"

Winrm protocol is running on the remote Windows host with this settings on the service:

```
AllowUnencrypted = false
        Auth
            Basic = true
            Kerberos = true
            Negotiate = true
            Certificate = false
            CredSSP = true
            CbtHardeningLevel = Relaxed
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = *
        IPv6Filter = *
        EnableCompatibilityHttpListener = false
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint
        AllowRemoteAccess = true
    Winrs
        AllowRemoteShellAccess = true
        IdleTimeout = 7200000
        MaxConcurrentUsers = 2147483647
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 2147483647
        MaxMemoryPerShellMB = 1024
        MaxShellsPerUser = 50
```

It is weird that we were able to run the job with NTLM authentication.

This setting was also enabled on the Windows server node.
Enable-WSManCredSSP -Role "Server"

Is there any clue to check further? Appreciate your comments on this.

**Comment by jborean93** [comment]
I've seen this issue once before but unfortunately I cannot remember what the actual cause of it was. This is happening on the first step of the CredSSP authentication phase and is surprising as it's a simple TLS handshake step.

Are you able to;

* Look at the security event logs and see if there are any failure entries around the time you run this
* Look at the application event logs and see if there are any errors, in particular around certificates or SChannel when you run this

Thanks

**Comment by mcassaniti** [comment]
Generally I've set the WinRM service certificate thumbprint to empty and this has resolved the issue, but from what you've shown already this has been cleared. Not sure how to help further, but I hope this helps someone else.

**Comment by jborean93** [comment]
@mcassaniti thanks for the input, if you are seeing issues when you've manually set the thumbprint for the CredSSP server then that could be due to permissions issues on the cert itself. You would need to make sure `Network Service` has permissions to read the private key for that cert. Here's a basic overview of how to set those permissions https://www.citrix.com/blogs/2011/06/20/how-to-get-the-certificate-thumbprint-and-adding-permissions-for-particular-user-using-powershell/.

**Comment by jborean93** [comment]
Interesting, I've never really played around too much with an explicit cert so I'll definitely keep an eye out. There's no explicit checks in the requests-credssp code to match the subject name of the cert right now but I could certainly add it if needed.

**Comment by jborean93** [comment]
@cwaltherf were you able to solve this issue?

**Comment by g-sandeep** [comment]
I am facing similar issue. Trying to run win ping command from ansible tower to windows 2012 server via winrm
{
    "msg": "credssp: Received error status from the server: (3221225581) STATUS_LOGON_FAILURE 0xc000006d",
    "unreachable": true,
    "changed": false

**Comment by fanuelsen** [comment]
i managed to solve the tls handshake problem to windows 2012 server via winrm with assigning the certififacte thumbprint directly on winrm service.  

winrm set winrm/config/service '@{CertificateThumbprint="certificatethumbprinthere"}'
