### ISSUE TITLE
error: [Errno 2] No such file or directory: 'LICENSE' when attempting to build a wheel

### ISSUE THREAD

**Issue by shields478** [jborean93/requests-credssp#13]
I'm getting the No file found (LICENSE) when attempting to build a wheel.

The specific command is as follows
Error building wheel for requests-credssp 1.0.2: Command '['/pyenv/versions/3.6.2/bin/pip', 'wheel', '--no-cache-dir', '--no-deps', '--no-binary', ':all:', '--index-url', '**local pypi mirror**', '-w', '/tmp/tmp1rphi_pp', 'requests-credssp==1.0.2', '--build-option', '--universal']' returned non-zero exit status 1.

**Comment by jborean93** [comment]
I've just added the `MANIFEST.in` file to include the license and changelog which should take affect in the next release https://github.com/jborean93/requests-credssp/pull/14. If this is still an issue when that release comes out let me know and I'll look into again.
