### ISSUE TITLE
Timeline for Kerberos support

### ISSUE THREAD

**Issue by mklemm2** [jborean93/requests-credssp#6]
Hi jborean93,

Is Kerberos support something that will be implemented rather soon or is this more a project for "someday"?

Thanks, Marcus

**Comment by jborean93** [comment]
There is no set timeline, I'm waiting for some downstream library changes so I can easily use Kerberos encryption without implementing the required code myself. Once that is in it shouldn't it be too hard to add support for Kerberos auth in here.

**Comment by mklemm2** [comment]
Thanks!

**Comment by jborean93** [comment]
@mklemm2 it took a bit longer than I expected but Kerberos authentication (with other features) have been added in the PR https://github.com/jborean93/requests-credssp/pull/7. It requires some extra packages which can be installed with `pip install requests-credssp[keberos]` but should work once that is installed.
